# Generated by Django 6.0.4 on 2026-05-05 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPDSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('text_en', models.TextField()),
                ('text_si', models.TextField(blank=True)),
                ('text_ta', models.TextField(blank=True)),
                ('is_reverse_scored', models.BooleanField(default=False, help_text='Questions 3,5,6,7,8,9,10 use reverse scoring')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EPDSAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=120)),
                ('text_si', models.CharField(blank=True, max_length=120)),
                ('text_ta', models.CharField(blank=True, max_length=120)),
                ('score_value', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='screening.epdsquestion')),
            ],
            options={
                'ordering': ['score_value'],
            },
        ),
        migrations.CreateModel(
            name='EPDSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('tier', models.CharField(choices=[('doing_well', 'Doing Well'), ('needs_attention', 'Needs Attention'), ('seek_support', 'Seek Support Now')], max_length=20)),
                ('responses', models.JSONField(default=dict, help_text='Stores {question_id: answer_option_id} mapping')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epds_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
