# Generated by Django 6.0.4 on 2026-05-05 07:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('display_alias', models.CharField(blank=True, help_text='Anonymous display name for community', max_length=60)),
                ('is_anonymous_mode', models.BooleanField(default=False, help_text='Hide real name in community')),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('si', 'සිංහල'), ('ta', 'தமிழ்')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_due_date', models.DateField(blank=True, null=True)),
                ('baby_birth_date', models.DateField(blank=True, null=True)),
                ('is_first_time_mother', models.BooleanField(default=True)),
                ('province', models.CharField(blank=True, choices=[('western', 'Western'), ('central', 'Central'), ('southern', 'Southern'), ('northern', 'Northern'), ('eastern', 'Eastern'), ('north_western', 'North Western'), ('north_central', 'North Central'), ('uva', 'Uva'), ('sabaragamuwa', 'Sabaragamuwa')], max_length=30)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('share_data_for_research', models.BooleanField(default=False)),
                ('daily_reminder_time', models.TimeField(blank=True, null=True)),
                ('weekly_screening_reminder', models.BooleanField(default=True)),
                ('journal_pin', models.CharField(blank=True, help_text='Hashed PIN for journal lock', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
