# Generated by Django 6.0.4 on 2026-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('myth_busting', 'Myth Busting'), ('understanding_ppd', 'Understanding PPD'), ('for_family', 'For Partners & Family'), ('treatment', 'Treatment Options'), ('general', 'General')], default='general', max_length=30)),
                ('summary', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('available_hours', models.CharField(default='24/7', max_length=60)),
                ('languages', models.CharField(default='Sinhala, Tamil, English', max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-is_featured', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PHMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('moh_office', models.CharField(blank=True, help_text='MOH office name', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PHM Contact',
                'verbose_name_plural': 'PHM Contacts',
                'ordering': ['province', 'district'],
            },
        ),
    ]
